receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# Removed 'prometheus' receiver — not needed unless scraping external targets

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "localhost:4317"
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
